[tasks.dev]
command = "watchexec"
args = ["-r", "-w=src", "cargo", "run"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.preview]
command = "./target/release/${CARGO_MAKE_CRATE_NAME}"
